### ISSUE TITLE
Can't Pass Tuple of Arbitrary `Class`es

### ISSUE THREAD

**Issue by jnhyatt** [Anti-Alias/bevy_ui_dsl#3]
Hi! Thanks for making this crate, it simplifies UI creation by an order of magnitude. `bevy_ui` is a improving quickly, but it sorely needs 3rd-party help, and I'm grateful there are community members providing this support.

I plan on using this crate for a project, and to that end, I'd like to help contribute if you're accepting help. I just recently ran into an issue that I was hoping to help fix. For UI classes, functions of the form `fn xxx(b: &mut XxxBundle)` have `Class<XxxBundle>` implemented for them automatically. There are also times when I want more configurable functionality:

```rust
pub struct BgColor(pub Color);

impl Class<NodeBundle> for BgColor {
    fn apply(self, b: &mut NodeBundle) {
        b.background_color = self.0.into();
    }
}
```

This works as expected:

```rust
node(BgColor(Color::RED), p, |p| { ...
```

However, it can't be combined with other classes, whether they're functions or structs implementing `Class`:

```rust
node((BgColor(Color::RED), c_half), p, |p| { ... // ERROR
```

I've already implemented a very simple fix. If you're open to contributions, I'm opening up a PR implements `Class<B>` for all tuples of the form `(Class<B>, ...)`. This would allow the above to compile and work as expected. If you're not open to PRs, let me know and I'll refrain from submitting any more.

Thanks!

**Comment by Anti-Alias** [comment]
I'll definitely take a look after work. Thanks for contributing! Glad this tiny crate is getting some use.
