### ISSUE TITLE
How to callback of add listener ?

### ISSUE THREAD

**Issue by zzhgithub** [Anti-Alias/bevy_ui_dsl#6]
Firstly, What a great lib. It's useful.
I just starting work on ui of my game. how lucky I am to find your lib.

I just wandering How to do in some case：
I want to make a  toolbar like minecraft. when mouse click of keydown to active a block of the toolbar.
can the lib have a function that can make different image and a state binding ？（PS: just like react or vue).
If not. How can i now change ui when something happened?  such as visiable or hide .

Finally, What a  great project!!!! Thanks

**Comment by Anti-Alias** [comment]
Glad you like it!

This crate offers no functionality outside of what bevy_ui can already do. It only makes your UI code "tidy".
You'll have to handle UI interactions the same way you do in bevy_ui: By making a system that listens for interactions. No React or Vue experience here, I'm afraid 😭.

The example.rs file shows how you can react to "Interactions" in a system. It's not pleasant, but it should work for now.
Say you wanted to change the color of another UI element when a button gets clicked. In the system, you'd:

1) Query for the entity you want to change.
2) Update the BackgroundColor of that entity's Style component.

Hopefully the Bevy team will figure out a way to make UI interactions more pleasant.

**Comment by Anti-Alias** [comment]
Closed as question has been addressed.
