### ISSUE TITLE
Separate inline/non-inline widgets

### ISSUE THREAD

**Issue by musjj** [Anti-Alias/bevy_ui_dsl#9]
It'd be nice if inline and non-inline widgets can be accessed via separate modules. This avoids the awkward `*i` naming scheme which is hard to read IMO.

Exposing the widgets via a module in general would also allow more flexibility in coding styles (some user might prefer to access the widgets using a namespace).

For example:

```rust
use bevy_ui_dsl::widgets;
use bevy_ui_dsl::widgets::inline;;

widgets::root // non-inline
inline::root // inline
```

```rust
use bevy_ui_dsl::widgets::*;;

root // for those who don't want to use namespaces
```

**Comment by Anti-Alias** [comment]
This could be cumbersome in situations where you use a combination of both, and typing out the namespace isn't terribly ergonomic.

**Comment by Anti-Alias** [comment]
I've been thinking about it, and honestly, if one wished to use both, they could always use the "import X as iX" if they wanted to, so maybe it isn't really an ergonomic issue at all. This repo hasn't been a priority for me, with my main goal keeping it up-to-date with the latest version of Bevy. PRs are welcome, though, so if you're feeling generous and want to add this for me, I'd be happy to accept it :)
